doctrine:
    dbal:

        #user: 'dev'
        #password: 'l0l0t1ng@2209'
        #host: '::1'
        #port: '1433'
        #dbname: 'SMS_CLIENT'
        #driver: 'sqlsrv'
        #charset: 'UTF-8'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        second_level_cache:
            enabled: true
            regions:
                write_rare:
                    # expire automatically after 10 days
                    lifetime: 864000
                    # let's use app's main cache pool
                    # (in my case it's using Redis)
                    cache_driver: { type: service, id: cache.app }

                append_only:
                    # expire automatically after 100 days
                    lifetime: 8640000
                    # let's use app's main cache pool
                    # (in my case it's using Redis)
                    cache_driver: { type: service, id: cache.app }
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
